### ISSUE TITLE
OOA

### ISSUE THREAD

**Issue by Jian-Min-Huang** [Game-as-a-Service/Yu-Gi-Oh#12]
https://www.yugioh-card.com/hk/howto/?lang=en
https://www.db.yugioh-card.com/yugiohdb/card_search.action

**Comment by kehao-chen** [comment]
後來重新思考一下，Monster Card 的 Attribute，與 Spell/Trap Card 相互對應的是 Icon，而 Monster Type 實際是 Moster Card 特有的 property。因此個人會認為在用詞上應維持使用 Icon，而不應該額外創造 Spell Type/Trap Type 的名詞，至於是否要共用一組 enum type 來列出 Icon 的值，這點倒是可以討論

**Comment by Jian-Min-Huang** [comment]
同意，我一起放在這次 PR 了

https://github.com/Game-as-a-Service/Yu-Gi-Oh/pull/25
