### ISSUE TITLE
遊戲流程

### ISSUE THREAD

**Issue by Jian-Min-Huang** [Game-as-a-Service/Yu-Gi-Oh#6]

**Comment by kehao-chen** [comment]
遊戲王的初代規則相當簡略，可以從下方敘述中略知一二
> - 高等級怪獸不須祭品即可召喚。
> - 一回合只能從手牌打出一張魔法、陷阱卡。
> - 只能以場上的怪獸作為融合素材。
> - 其中一方牌組耗盡而無法繼續決鬥的場合，由生命值較多的一方獲勝。
> - 手牌無上限。
> - 先攻第一回合不能抽牌。
> - 三戰兩勝MATCH戰中出現兩次平局的場合，該MATCH本身作為平局收場。
> - 備牌10張。
> - 陷阱卡沒有標註「發動後此卡破壞」的話就會殘留在場上。
> - 融合怪獸被效果返回的場合，先回到手牌然後再回到融合牌組。
> - 不能從手牌發動誘發即時效果，而是要放到場上來發動。
>
> —— Ref. [巴哈姆特 - 遊戲王規則演進](https://forum.gamer.com.tw/Co.php?bsn=00725&sn=278909)


個人認為遊戲流程大致可簡化為四個階段：
```mermaid
stateDiagram-v2
 

S1: 抽牌階段
note right of S1
    * 非先攻第一回合，玩家進行抽牌
    * 若玩家無牌可抽進行勝負判斷
end note
S2: 準備階段
note right of S2
    * 玩家可召喚怪獸卡
    * 玩家可放置魔法卡/陷阱卡
    * 玩家可發動魔法卡
end note
S3: 攻擊階段
note right of S3
    * 玩家場上的怪獸卡可進行攻擊宣告
end note
S4: 結束階段
note right of S4
    * 玩家宣告回合結束
end note

S1 --> S2
S2 --> S3
S3 --> S4
S4 --> S1
```

**Comment by kehao-chen** [comment]
暫時先以個人理解，定出這些 Domain Event，若有時間再來補齊內容  
![image](https://user-images.githubusercontent.com/13099052/197342934-98da6787-212d-4a35-b090-a61dad690265.png)

**Comment by m1a2st** [comment]
我是把第一回分割出來，因為第一回合流程不太一樣，只有主階沒有戰鬥階段跟主階二，我在想牌組耗盡應該算在rule嗎？
![My first board](https://user-images.githubusercontent.com/100591800/197348100-9e637daf-fd27-4b60-b9ff-d5a646cf9bfe.jpg)

**Comment by kehao-chen** [comment]
個人思考的點在於，進入下一個階段或是結束回合，是需要玩家 (Actor) 明確作出宣言 (Command)，這點不論是在現實遊戲或是 Duel Links 都是通用的，因此進入到下一個階段會是 Domain Event

**Comment by kehao-chen** [comment]
針對牌堆無卡的流程處理，在個人的想象中，是當已進入抽卡階段這個 Domain Event 發生，會有額外的 Policy 去觸發遊戲結束判斷這個 Command (系統執行)

![image](https://user-images.githubusercontent.com/13099052/197379757-f08b3ada-c7cf-4e84-8dc7-5c7c918796d9.png)

**Comment by hsinshengsouth** [comment]
我大致理解的流程會長這樣，跟大家應該也差不多
![game_flow](https://user-images.githubusercontent.com/41569336/197392535-38e43f4f-791a-4d49-94a4-6c46c933807c.jpg)
